apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-dags-sync
  namespace: argocd # Or your Argo CD namespace
spec:
  project: default
  source:
    repoURL: https://github.com/maccam912/airflow-dags.git # Replace with your repo URL
    targetRevision: main # Or your branch
    path: dags # Path to the dags directory in your git repo
  destination:
    server: https://kubernetes.default.svc # Defaults to the current cluster
    namespace: airflow # Replace with your Airflow namespace
  syncPolicy:
    automated:
      prune: true # Delete resources no longer in Git
      selfHeal: true # Automatically correct drift
    #syncOptions:
    #  - CreateNamespace=true # Create namespace if it doesn't exist
    resourceTrackingMethod: label