apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dags-sync-cronjob
  namespace: airflow
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            system/nixos: "true"
          containers:
          - name: git-sync
            image: alpine/git
            command:
              - /bin/sh
              - -c
              - |
                cd /mnt/dags && \
                if [ -d ".git" ]; then
                  git pull
                else
                  git clone --depth=1 https://github.com/maccam912/airflow-dags.git .
                fi
            volumeMounts:
            - name: dags-volume
              mountPath: /mnt/dags
          restartPolicy: Never
          volumes:
          - name: dags-volume
            persistentVolumeClaim:
              claimName: airflow-dags